"""
MCP Server Handlers for Fees Explainer Agent
============================================

Implements the actual MCP tool handlers for:
1. append_to_notes - Appends fee explanations to notes file
2. create_email_draft - Creates email draft (no auto-send)
3. log_audit_entry - Logs audit trail

All handlers include approval-gating logic.
"""

import os
import json
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, Optional


class ApprovalRequired(Exception):
    """Exception raised when user approval is needed."""
    def __init__(self, tool_name: str, prompt: str, payload: Dict):
        self.tool_name = tool_name
        self.prompt = prompt
        self.payload = payload
        super().__init__(f"Approval required for {tool_name}")


class NotesHandler:
    """Handles notes/documentation operations."""

    def __init__(self, notes_file: str = "/home/user/fees_explanations.md"):
        self.notes_file = notes_file
        self._ensure_file_exists()

    def _ensure_file_exists(self):
        """Create notes file if it doesn't exist."""
        notes_path = Path(self.notes_file)
        if not notes_path.exists():
            notes_path.parent.mkdir(parents=True, exist_ok=True)
            with open(self.notes_file, 'w') as f:
                f.write("# Fee Explanations Log\n\n")
                f.write("Auto-generated by Fees Explainer Agent\n\n")
                f.write("---\n\n")

    def append_entry(
        self,
        entry_title: str,
        date: str,
        scenario: str,
        fee_details: list,
        last_checked: str,
        clarifiers: Optional[Dict] = None,
        approved: bool = False
    ) -> Dict[str, Any]:
        """
        Append a fee explanation entry to notes.

        Args:
            entry_title: Title of the entry
            date: ISO timestamp
            scenario: Fee scenario name
            fee_details: List of dicts with 'text' and 'source'
            last_checked: Date information was last verified
            clarifiers: Optional dict of questions and answers
            approved: Whether this action is pre-approved

        Returns:
            Dict with operation result

        Raises:
            ApprovalRequired: If approved=False
        """
        if not approved:
            raise ApprovalRequired(
                tool_name="append_to_notes",
                prompt=f"Do you want to append this fee explanation to your notes?\n\nTitle: {entry_title}\nScenario: {scenario}",
                payload={
                    "entry_title": entry_title,
                    "date": date,
                    "scenario": scenario,
                    "fee_details": fee_details,
                    "last_checked": last_checked,
                    "clarifiers": clarifiers
                }
            )

        # Format the entry
        entry_lines = [
            f"\n## {entry_title}\n",
            f"**Date:** {date}\n",
            f"**Scenario:** {scenario}\n",
            f"**Last Checked:** {last_checked}\n\n"
        ]

        if clarifiers:
            entry_lines.append("**Context:**\n")
            for question, answer in clarifiers.items():
                entry_lines.append(f"- Q: {question}\n")
                entry_lines.append(f"  A: {answer}\n")
            entry_lines.append("\n")

        entry_lines.append("**Fee Details:**\n\n")
        for i, detail in enumerate(fee_details, 1):
            entry_lines.append(f"{i}. {detail['text']}\n")
            entry_lines.append(f"   📎 Source: {detail['source']}\n\n")

        entry_lines.append("---\n\n")

        # Append to file
        with open(self.notes_file, 'a') as f:
            f.writelines(entry_lines)

        return {
            "status": "success",
            "tool": "append_to_notes",
            "message": f"Entry appended: {entry_title}",
            "file": self.notes_file,
            "bytes_written": sum(len(line) for line in entry_lines)
        }


class EmailHandler:
    """Handles email draft creation."""

    def __init__(self, drafts_dir: str = "/home/user/email_drafts"):
        self.drafts_dir = drafts_dir
        self._ensure_dir_exists()

    def _ensure_dir_exists(self):
        """Create drafts directory if it doesn't exist."""
        Path(self.drafts_dir).mkdir(parents=True, exist_ok=True)

    def create_draft(
        self,
        to: str,
        subject: str,
        body: str,
        draft_only: bool = True,
        approved: bool = False
    ) -> Dict[str, Any]:
        """
        Create an email draft (NEVER auto-sends).

        Args:
            to: Recipient email
            subject: Email subject
            body: Email body
            draft_only: Must be True (enforced)
            approved: Whether this action is pre-approved

        Returns:
            Dict with draft creation result

        Raises:
            ApprovalRequired: If approved=False
            ValueError: If draft_only=False
        """
        if not draft_only:
            raise ValueError("Auto-send is not allowed. draft_only must be True.")

        if not approved:
            raise ApprovalRequired(
                tool_name="create_email_draft",
                prompt=f"Do you want to create this email draft?\n\nTo: {to}\nSubject: {subject}\n\n(Draft will NOT be sent automatically)",
                payload={
                    "to": to,
                    "subject": subject,
                    "body": body[:200] + "..." if len(body) > 200 else body
                }
            )

        # Create draft file
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        draft_filename = f"draft_{timestamp}.eml"
        draft_path = os.path.join(self.drafts_dir, draft_filename)

        # Format as EML (RFC 822)
        eml_content = [
            f"To: {to}\n",
            f"Subject: {subject}\n",
            f"Date: {datetime.now().isoformat()}\n",
            f"X-Draft: true\n",
            f"X-Created-By: FeesExplainerAgent\n",
            "\n",
            body
        ]

        with open(draft_path, 'w') as f:
            f.writelines(eml_content)

        return {
            "status": "success",
            "tool": "create_email_draft",
            "message": f"Email draft created: {draft_filename}",
            "draft_path": draft_path,
            "to": to,
            "subject": subject,
            "auto_sent": False
        }


class AuditHandler:
    """Handles audit logging."""

    def __init__(self, audit_file: str = "/home/user/audit_log.jsonl"):
        self.audit_file = audit_file
        self._ensure_file_exists()

    def _ensure_file_exists(self):
        """Create audit log file if it doesn't exist."""
        audit_path = Path(self.audit_file)
        if not audit_path.exists():
            audit_path.parent.mkdir(parents=True, exist_ok=True)
            # JSONL format - no header needed
            audit_path.touch()

    def log_entry(
        self,
        who: str,
        when: str,
        action: str,
        details: Optional[Dict] = None,
        approved: bool = False
    ) -> Dict[str, Any]:
        """
        Log an audit trail entry.

        Args:
            who: Entity performing the action
            when: ISO timestamp
            action: Action description
            details: Optional metadata
            approved: Whether this action is pre-approved

        Returns:
            Dict with logging result

        Raises:
            ApprovalRequired: If approved=False
        """
        if not approved:
            raise ApprovalRequired(
                tool_name="log_audit_entry",
                prompt=f"Do you want to log this audit entry?\n\nWho: {who}\nAction: {action}",
                payload={
                    "who": who,
                    "when": when,
                    "action": action,
                    "details": details
                }
            )

        # Create audit entry
        audit_entry = {
            "who": who,
            "when": when,
            "action": action,
            "details": details or {},
            "logged_at": datetime.now().isoformat()
        }

        # Append as JSONL
        with open(self.audit_file, 'a') as f:
            f.write(json.dumps(audit_entry) + '\n')

        return {
            "status": "success",
            "tool": "log_audit_entry",
            "message": f"Audit entry logged: {action}",
            "file": self.audit_file,
            "entry_id": audit_entry["logged_at"]
        }


# MCP Server Interface
class MCPServer:
    """
    Main MCP server that orchestrates all handlers.

    Provides approval-gated access to Notes, Email, and Audit tools.
    """

    def __init__(self):
        self.notes = NotesHandler()
        self.email = EmailHandler()
        self.audit = AuditHandler()

    def execute_tool(
        self,
        tool_name: str,
        params: Dict[str, Any],
        approved: bool = False
    ) -> Dict[str, Any]:
        """
        Execute an MCP tool with approval gating.

        Args:
            tool_name: Name of the tool to execute
            params: Tool parameters
            approved: Whether action is pre-approved

        Returns:
            Dict with execution result

        Raises:
            ApprovalRequired: If approval is needed
            ValueError: If tool_name is invalid
        """
        params['approved'] = approved

        if tool_name == 'append_to_notes':
            return self.notes.append_entry(**params)
        elif tool_name == 'create_email_draft':
            return self.email.create_draft(**params)
        elif tool_name == 'log_audit_entry':
            return self.audit.log_entry(**params)
        else:
            raise ValueError(f"Unknown tool: {tool_name}")

    def get_approval_summary(self, tool_name: str, params: Dict[str, Any]) -> str:
        """
        Get human-readable summary for approval prompt.

        Args:
            tool_name: Name of the tool
            params: Tool parameters

        Returns:
            Formatted approval summary
        """
        if tool_name == 'append_to_notes':
            return f"Append to Notes: {params.get('entry_title')}\nScenario: {params.get('scenario')}"
        elif tool_name == 'create_email_draft':
            return f"Create Email Draft\nTo: {params.get('to')}\nSubject: {params.get('subject')}"
        elif tool_name == 'log_audit_entry':
            return f"Log Audit Entry\nAction: {params.get('action')}\nWho: {params.get('who')}"
        else:
            return f"Execute: {tool_name}"


# Example usage
if __name__ == '__main__':
    server = MCPServer()

    # Example 1: Try to append notes without approval
    try:
        result = server.execute_tool(
            'append_to_notes',
            {
                'entry_title': 'Test Entry',
                'date': datetime.now().isoformat(),
                'scenario': 'Exit Load Test',
                'fee_details': [
                    {'text': 'Test detail', 'source': 'https://example.com'}
                ],
                'last_checked': '2025-12-15'
            },
            approved=False
        )
    except ApprovalRequired as e:
        print(f"Approval Required: {e.prompt}")
        print(f"Payload: {json.dumps(e.payload, indent=2)}")

    # Example 2: Execute with approval
    result = server.execute_tool(
        'log_audit_entry',
        {
            'who': 'TestAgent',
            'when': datetime.now().isoformat(),
            'action': 'Test audit log',
            'details': {'test': True}
        },
        approved=True
    )
    print(f"\nAudit Log Result: {json.dumps(result, indent=2)}")
